version: '3.8'

services:
  bookingsystem1-postgres:
    container_name: bookingsystem1-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=QWE!@#asd123
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - bookingsystem1-postgres-volume:/var/lib/postgresql/data

volumes:
  bookingsystem1-postgres-volume:  
  
  